Add missing type declaration of spritesheet to Resource
Fix for this error: *ERROR: Property spritesheet does not exist on type Resource*
The code that triggers this error:
```
const theme: PIXI.loaders.Resource|undefined = PIXI.loader.resources["images/BH_Theme_01.json"];
const sheet: PIXI.Spritesheet|undefined = theme.spritesheet;
```

As a workaround until this is merged, augment pixi.js in the app or game project's `global.d.ts` file:
```
import * as PIXI from "pixi.js";
//augment pixi.js
declare module "pixi.js" {
	namespace loaders {
		export interface Resource {
			// FIXME: report bug to PIXI maintainers
			// ERROR: Property spritesheet does not exist on type Resource
			spritesheet?: PIXI.Spritesheet;
		}
	}
}
```